### ISSUE TITLE
Settings: set paths implicitly

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1396]
All settings keys except for `data` beneath `paths` should be set implicitly if they are nil. For example,
```yml
paths:
  data: data
  git_repositories: # nil
  symlinks: # nil
  commits: # nil
  git_home: # nil
```
should be interpreted as
```yml
paths:
  data: data
  git_repositories: data/repositories
  symlinks: data/git_daemon
  commits: data/commits
  git_home: data/git
```
