### ISSUE TITLE
brittle spec

### ISSUE THREAD

**Issue by 0robustus1** [ontohub/ontohub#755]
There is a specific [spec](https://github.com/ontohub/ontohub/blob/staging/spec/models/ontology_spec.rb#L17) related to deleting an ontology (and its file) which is brittle.

Brittle in this case means that it fails or is successful depending on the order of test execution (keep in mind that rspec randomizes test-execution order).

Here is the failing output:

```
Failures:

  1) Ontology when deleting a general ontology should delete the defining file as well
     Failure/Error: expect(ontology.repository.path_exists?(file)).to be_false
     NoMethodError:
       undefined method `tree' for nil:NilClass
     # ./lib/git_repository.rb:155:in `path_exists_rugged?'
     # ./lib/git_repository.rb:55:in `path_exists?'
     # ./app/models/repository/git_repositories.rb:117:in `path_exists?'
     # ./spec/models/ontology_spec.rb:20:in `block (4 levels) in <top (required)>'
```

This could be caused by the fact, that the repository is, in this case, not backed by a git-repository (and therefore the head-commit is `nil`).
@eugenk could you take a look at this?
